// PDF report generator for CloudOptics
// Uses jspdf + jspdf-autotable (client-side only)

const BRAND_PURPLE = [121, 44, 162];
const BRAND_LIGHT  = [220, 203, 255];
const DARK_NAVY    = [17, 24, 68];
const GRAY_TEXT    = [100, 110, 130];
const GRAY_BG      = [249, 247, 247];
const WHITE        = [255, 255, 255];

function drawPageFrame(doc, pageNum, totalPages, title = "") {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // Top accent bar
  doc.setFillColor(...BRAND_PURPLE);
  doc.rect(0, 0, W, 8, "F");

  // Header area background
  doc.setFillColor(250, 248, 254);
  doc.rect(0, 8, W, 22, "F");

  // Logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_PURPLE);
  doc.text("CloudOptics", 14, 22);

  // Header title (right-aligned)
  if (title) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...GRAY_TEXT);
    doc.text(title, W - 14, 22, { align: "right" });
  }

  // Thin separator line
  doc.setDrawColor(...BRAND_LIGHT);
  doc.setLineWidth(0.3);
  doc.line(14, 30, W - 14, 30);

  // Footer
  doc.setFillColor(250, 248, 254);
  doc.rect(0, H - 14, W, 14, "F");
  doc.setDrawColor(...BRAND_LIGHT);
  doc.setLineWidth(0.3);
  doc.line(14, H - 14, W - 14, H - 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...GRAY_TEXT);
  doc.text("Generated by CloudOptics • Confidential", 14, H - 5);
  doc.text(`Page ${pageNum} of ${totalPages}`, W - 14, H - 5, { align: "right" });

  // Bottom accent bar
  doc.setFillColor(...BRAND_PURPLE);
  doc.rect(0, H - 2, W, 2, "F");
}

function sectionTitle(doc, text, y) {
  doc.setFillColor(...BRAND_PURPLE);
  doc.roundedRect(14, y - 5, 4, 12, 1, 1, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...DARK_NAVY);
  doc.text(text, 22, y + 3);
  return y + 16;
}

export async function generatePDF() {
  const { default: jsPDF }        = await import("jspdf");
  const { default: autoTable }    = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();

  const now        = new Date();
  const dateStr    = now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  const timeStr    = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  // ── Fetch all data from APIs ─────────────────────────────────────────────────
  let summaryData = null, trendsData = [], donutData = [], resourcesData = [], formattedAlerts = [], recommendations = [];
  const donutFilter = "All";

  try {
    const [summaryRes, trendsRes, servicesRes, resourcesRes, alertsRes, recsRes] = await Promise.allSettled([
      fetch("/api/dashboard/summary"),
      fetch("/api/dashboard/trends"),
      fetch("/api/dashboard/services"),
      fetch("/api/resources"),
      fetch("/api/optimization/alerts"),
      fetch("/api/recommendations"),
    ]);

    if (summaryRes.status === "fulfilled" && summaryRes.value.ok) {
      summaryData = await summaryRes.value.json();
    }
    if (trendsRes.status === "fulfilled" && trendsRes.value.ok) {
      trendsData = await trendsRes.value.json();
    }
    if (servicesRes.status === "fulfilled" && servicesRes.value.ok) {
      const servicesJson = await servicesRes.value.json();
      const totalServiceCost = (servicesJson || []).reduce((sum, s) => sum + (s.value || 0), 0);
      donutData = (servicesJson || []).map((s, i) => ({
        name: s.service || s._id || `Service ${i + 1}`,
        value: totalServiceCost > 0 ? Math.round((s.value / totalServiceCost) * 1000) / 10 : 0,
        rawCost: s.value || 0,
        colorHex: ["792CA2", "9A4DCC", "C084FC", "6B21A8", "A855F7"][i % 5],
      }));
    }
    if (resourcesRes.status === "fulfilled" && resourcesRes.value.ok) {
      resourcesData = await resourcesRes.value.json();
    }
    if (alertsRes.status === "fulfilled" && alertsRes.value.ok) {
      const alertsJson = await alertsRes.value.json();
      formattedAlerts = Array.isArray(alertsJson) ? alertsJson : (alertsJson.alerts || []);
    }
    if (recsRes.status === "fulfilled" && recsRes.value.ok) {
      const recsJson = await recsRes.value.json();
      recommendations = recsJson.recommendations || [];
    }
  } catch (err) {
    console.error("Failed to fetch report data:", err);
  }

  // ── Compute KPI trends from trends data ──────────────────────────────────────
  const calcTrend = (key) => {
    if (!trendsData || trendsData.length < 14) return { trend: "—", label: "vs last week" };
    const week4 = trendsData.slice(-7).reduce((s, t) => s + (t[key] || 0), 0);
    const week3 = trendsData.slice(-14, -7).reduce((s, t) => s + (t[key] || 0), 0);
    if (week3 === 0) return { trend: "0.0%", label: "vs last week" };
    const pct = ((week4 - week3) / week3) * 100;
    return { trend: `${pct > 0 ? "+" : ""}${pct.toFixed(1)}%`, label: "vs last week" };
  };
  const kpiTrends = {
    totalSpend:   calcTrend("spend"),
    computeSpend: calcTrend("computeSpend"),
    storageSpend: calcTrend("storageSpend"),
    totalSavings: {
      trend: summaryData?.totalSpend > 0 ? `${((summaryData.totalSavings / summaryData.totalSpend) * 100).toFixed(1)}%` : "0.0%",
      label: "of spend"
    },
  };

  const TOTAL_PAGES = recommendations.length > 0 ? 6 : 5;


  // ── PAGE 1: COVER ───────────────────────────────────────────────────────────
  // Full purple cover background
  doc.setFillColor(...BRAND_PURPLE);
  doc.rect(0, 0, W, 297, "F");

  // Large decorative circle
  doc.setFillColor(154, 77, 204);
  doc.circle(W + 20, 60, 80, "F");
  doc.setFillColor(100, 30, 140);
  doc.circle(-20, 230, 70, "F");

  // CloudOptics logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(255, 255, 255);
  doc.text("CloudOptics", 20, 70);

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.setTextColor(220, 203, 255);
  doc.text("Cloud Cost Intelligence Platform", 20, 82);

  // Divider line
  doc.setDrawColor(255, 255, 255, 0.4);
  doc.setLineWidth(0.5);
  doc.line(20, 95, W - 20, 95);

  // Report title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text("Dashboard Report", 20, 115);

  // Environment badge
  doc.setFillColor(255, 255, 255, 0.15);
  doc.roundedRect(20, 124, 60, 10, 3, 3, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(`Environment: ${donutFilter || "All"}`, 50, 131, { align: "center" });

  // Metadata block
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(220, 203, 255);
  doc.text(`Generated: ${dateStr}  ·  ${timeStr}`, 20, 148);

  // KPI snapshot at bottom of cover
  const kpiItems = [
    { label: "Total Spend",   value: `$${(summaryData?.totalSpend ?? 0).toFixed(2)}` },
    { label: "Compute Spend", value: `$${(summaryData?.computeSpend ?? 0).toFixed(2)}` },
    { label: "Storage Spend", value: `$${(summaryData?.storageSpend ?? 0).toFixed(2)}` },
    { label: "Total Savings", value: `$${(summaryData?.totalSavings ?? 0).toFixed(2)}` },
  ];

  const cardW = (W - 40 - 12) / 4;
  kpiItems.forEach((kpi, i) => {
    const x = 20 + i * (cardW + 4);
    doc.setFillColor(255, 255, 255, 0.12);
    doc.roundedRect(x, 175, cardW, 34, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(255, 255, 255);
    doc.text(kpi.value, x + cardW / 2, 191, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(220, 203, 255);
    doc.text(kpi.label, x + cardW / 2, 200, { align: "center" });
  });

  // "Confidential" footer on cover
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255, 0.5);
  doc.text("CONFIDENTIAL  ·  CloudOptics Dashboard Report", W / 2, 285, { align: "center" });

  // ── PAGE 2: KPI SUMMARY ──────────────────────────────────────────────────────
  doc.addPage();
  drawPageFrame(doc, 2, TOTAL_PAGES, "KPI Summary");

  let y = 42;
  y = sectionTitle(doc, "Key Performance Indicators", y);

  const kpiRows = [
    ["Total Spend",   `$${(summaryData?.totalSpend ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`,   kpiTrends?.totalSpend?.trend ?? "—",   kpiTrends?.totalSpend?.label ?? ""],
    ["Compute Spend", `$${(summaryData?.computeSpend ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`, kpiTrends?.computeSpend?.trend ?? "—", kpiTrends?.computeSpend?.label ?? ""],
    ["Storage Spend", `$${(summaryData?.storageSpend ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`, kpiTrends?.storageSpend?.trend ?? "—", kpiTrends?.storageSpend?.label ?? ""],
    ["Total Savings", `$${(summaryData?.totalSavings ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`, kpiTrends?.totalSavings?.trend ?? "—", kpiTrends?.totalSavings?.label ?? ""],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Change", "Period"]],
    body: kpiRows,
    margin: { left: 14, right: 14 },
    styles: { fontSize: 9, cellPadding: 4, font: "helvetica" },
    headStyles: {
      fillColor: BRAND_PURPLE,
      textColor: WHITE,
      fontStyle: "bold",
      halign: "left",
    },
    alternateRowStyles: { fillColor: [248, 244, 255] },
    columnStyles: {
      0: { fontStyle: "bold", textColor: DARK_NAVY },
      1: { halign: "right" },
      2: { halign: "center", fontStyle: "bold" },
    },
    didParseCell(data) {
      if (data.column.index === 2 && data.section === "body") {
        const v = data.cell.text[0] || "";
        if (v.startsWith("-")) data.cell.styles.textColor = [220, 38, 38];
        else if (v.startsWith("+")) data.cell.styles.textColor = [22, 163, 74];
      }
    },
  });
  y = doc.lastAutoTable.finalY + 6;

  // ── PAGE 3: COST DISTRIBUTION ───────────────────────────────────────────────
  doc.addPage();
  drawPageFrame(doc, 3, TOTAL_PAGES, "Cost Distribution");

  y = 42;
  y = sectionTitle(doc, "Cost Distribution by Service", y);

  const distRows = (donutData || []).map((item) => [
    item.name,
    `${item.value}%`,
    `$${(item.rawCost ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2 })}`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Service", "Share", "Estimated Cost"]],
    body: distRows,
    margin: { left: 14, right: 14 },
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: BRAND_PURPLE, textColor: WHITE, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 244, 255] },
    columnStyles: {
      0: { fontStyle: "bold", textColor: DARK_NAVY },
      1: { halign: "center" },
      2: { halign: "right" },
    },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 0) {
        const item = donutData?.[data.row.index];
        if (item?.colorHex) {
          const r = parseInt(item.colorHex.slice(1, 3), 16);
          const g = parseInt(item.colorHex.slice(3, 5), 16);
          const b = parseInt(item.colorHex.slice(5, 7), 16);
          data.cell.styles.fillColor = [r, g, b];
          data.cell.styles.textColor = WHITE;
        }
      }
    },
  });

  // ── PAGE 4: RESOURCES ────────────────────────────────────────────────────────
  doc.addPage();
  drawPageFrame(doc, 4, TOTAL_PAGES, "Resources");

  y = 42;
  y = sectionTitle(doc, "All Cloud Resources", y);

  const resourceRows = (resourcesData || []).slice(0, 50).map((r) => [
    r.name || r.resourceId || "—",
    r.region || "—",
    r.service || "—",
    r.environment || "—",
    r.status || "Active",
    `$${(r.cost ?? 0).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Resource ID", "Region", "Service", "Environment", "Status", "Cost/mo"]],
    body: resourceRows,
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: BRAND_PURPLE, textColor: WHITE, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 244, 255] },
    columnStyles: {
      0: { fontStyle: "bold", textColor: DARK_NAVY, cellWidth: 44 },
      5: { halign: "right" },
    },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 4) {
        const val = data.cell.text[0];
        if (val === "Running")  data.cell.styles.textColor = [22, 163, 74];
        else if (val === "Stopped") data.cell.styles.textColor = [156, 163, 175];
        else data.cell.styles.textColor = [220, 38, 38];
      }
    },
  });

  // ── PAGE 5: ALERTS ───────────────────────────────────────────────────────────
  doc.addPage();
  drawPageFrame(doc, 5, TOTAL_PAGES, "Optimization Alerts");

  y = 42;
  y = sectionTitle(doc, "Optimization Alerts", y);

  const alertRows = (formattedAlerts || []).slice(0, 40).map((a) => [
    `${a.type || "—"} — ${a.resourceId || "—"}`,
    a.severity || "—",
    a.type || "—",
    a.status || "unresolved",
    a.message || "—",
  ]);

  const severityColor = (s) => {
    if (s === "Critical") return [220, 38, 38];
    if (s === "High")     return [234, 88, 12];
    if (s === "Medium")   return [202, 138, 4];
    return [22, 163, 74];
  };

  autoTable(doc, {
    startY: y,
    head: [["Alert", "Severity", "Category", "Status", "Details"]],
    body: alertRows,
    margin: { left: 14, right: 14 },
    styles: { fontSize: 7.5, cellPadding: 3, overflow: "linebreak" },
    headStyles: { fillColor: BRAND_PURPLE, textColor: WHITE, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 244, 255] },
    columnStyles: {
      0: { fontStyle: "bold", textColor: DARK_NAVY, cellWidth: 38 },
      1: { halign: "center", cellWidth: 20 },
      2: { cellWidth: 24 },
      3: { cellWidth: 18, halign: "center" },
      4: { cellWidth: "auto" },
    },
    didParseCell(data) {
      if (data.section === "body" && data.column.index === 1) {
        data.cell.styles.textColor = severityColor(data.cell.text[0]);
        data.cell.styles.fontStyle = "bold";
      }
    },
  });

  // ── PAGE 6: RECOMMENDATIONS ──────────────────────────────────────────────────
  if (recommendations.length > 0) {
    doc.addPage();
    drawPageFrame(doc, 6, TOTAL_PAGES, "Optimization Recommendations");

    y = 42;
    y = sectionTitle(doc, "Cost Optimization Recommendations", y);

    const recommendationRows = recommendations.map((r) => [
      r.title || "—",
      r.category || "—",
      r.impact || "—",
      `$${(r.potentialSavings ?? 0).toFixed(2)}`,
      r.resourceId || "—",
      r.description || "—",
    ]);

    const impactColor = (i) => {
      if (i === "High") return [220, 38, 38];
      if (i === "Medium") return [202, 138, 4];
      return [22, 163, 74];
    };

    autoTable(doc, {
      startY: y,
      head: [["Recommendation", "Category", "Impact", "Savings/mo", "Resource ID", "Description"]],
      body: recommendationRows,
      margin: { left: 14, right: 14 },
      styles: { fontSize: 7.5, cellPadding: 3, overflow: "linebreak" },
      headStyles: { fillColor: BRAND_PURPLE, textColor: WHITE, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [248, 244, 255] },
      columnStyles: {
        0: { fontStyle: "bold", textColor: DARK_NAVY, cellWidth: 35 },
        1: { cellWidth: 20 },
        2: { halign: "center", cellWidth: 16 },
        3: { halign: "right", cellWidth: 22 },
        4: { cellWidth: 32 },
        5: { cellWidth: "auto" },
      },
      didParseCell(data) {
        if (data.section === "body" && data.column.index === 2) {
          data.cell.styles.textColor = impactColor(data.cell.text[0]);
          data.cell.styles.fontStyle = "bold";
        }
      },
    });
  }

  // Save
  const filename = `CloudOptics_Report_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
